openapi: 3.0.3
info:
  title: AI Assistant Chat API
  description: API for the AI Assistant Chat feature in the task management app
  version: 1.0.0
  contact:
    name: Task Management App Team
    email: dev@taskmanager.example.com
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server
  - url: https://api.taskmanager.example.com/v1
    description: Production server

paths:
  /chat/send:
    post:
      summary: Send a message to the AI assistant
      description: Sends a user message to the AI assistant and returns the response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '200':
          description: Successfully received response from AI assistant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMessageResponse'
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

  /conversations:
    post:
      summary: Create a new conversation
      description: Starts a new conversation thread
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConversationRequest'
      responses:
        '201':
          description: Conversation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

  /conversations/{conversationId}:
    get:
      summary: Get conversation details
      description: Retrieve details of a specific conversation
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the conversation
      responses:
        '200':
          description: Conversation details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Conversation not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

  /conversations/{conversationId}/messages:
    get:
      summary: Get conversation messages
      description: Retrieve all messages in a conversation
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the conversation
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
          description: Maximum number of messages to return
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: Number of messages to skip
      responses:
        '200':
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesResponse'
        '404':
          description: Conversation not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

components:
  schemas:
    SendMessageRequest:
      type: object
      required:
        - conversation_id
        - content
      properties:
        conversation_id:
          type: string
          format: uuid
          description: ID of the conversation to add the message to
        content:
          type: string
          maxLength: 10000
          description: The message content from the user
        message_type:
          type: string
          enum: [task_related, greeting, non_task]
          description: Optional hint about the message type

    SendMessageResponse:
      type: object
      required:
        - message
        - response
        - conversation_id
      properties:
        message:
          $ref: '#/components/schemas/Message'
        response:
          $ref: '#/components/schemas/Response'
        conversation_id:
          type: string
          format: uuid
          description: ID of the conversation

    CreateConversationRequest:
      type: object
      properties:
        initial_message:
          type: string
          description: Optional first message to start the conversation

    Conversation:
      type: object
      required:
        - conversation_id
        - created_at
        - updated_at
        - status
      properties:
        conversation_id:
          type: string
          format: uuid
          description: Unique identifier of the conversation
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated
        status:
          type: string
          enum: [active, archived, suspended]
          description: Current status of the conversation
        metadata:
          type: object
          additionalProperties: true
          description: Additional metadata about the conversation

    Message:
      type: object
      required:
        - message_id
        - conversation_id
        - sender_type
        - content
        - timestamp
      properties:
        message_id:
          type: string
          format: uuid
          description: Unique identifier of the message
        conversation_id:
          type: string
          format: uuid
          description: ID of the conversation this message belongs to
        sender_type:
          type: string
          enum: [user, ai_assistant]
          description: Who sent the message
        content:
          type: string
          description: The message content
        timestamp:
          type: string
          format: date-time
          description: When the message was sent
        message_type:
          type: string
          enum: [task_related, greeting, non_task, response]
          description: Classification of the message

    Response:
      type: object
      required:
        - response_id
        - content
        - generated_at
        - response_type
      properties:
        response_id:
          type: string
          format: uuid
          description: Unique identifier of the response
        content:
          type: string
          description: The AI assistant's response content
        generated_at:
          type: string
          format: date-time
          description: When the response was generated
        response_type:
          type: string
          enum: [task_guidance, greeting, boundary_setting]
          description: Type of response provided
        processing_time_ms:
          type: integer
          description: Time taken to generate the response in milliseconds
        confidence_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Confidence in the appropriateness of the response

    MessagesResponse:
      type: object
      required:
        - messages
        - total_count
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        total_count:
          type: integer
          description: Total number of messages in the conversation

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT